### ISSUE TITLE
show version in app?

### ISSUE THREAD

**Issue by NMAAHC** [LibraryOfCongress/embARC#1]
Can there be an "about embARC" option under the embARC menu? It would be great to access the version and release date (and other stuff) about the app from within the app. Perhaps it is already there somewhere?

**Comment by kmurmur** [comment]
Good idea! Let me look into it. Thanks for the suggestion

**Comment by kmurmur** [comment]
So it should already be there - do you see these (screenshots below)?

![Screen Shot 2020-01-27 at 1 49 08 PM](https://user-images.githubusercontent.com/26974622/73208669-d6f8c380-4114-11ea-9ee9-1054e9f201a0.png)
![Screen Shot 2020-01-27 at 1 48 06 PM](https://user-images.githubusercontent.com/26974622/73208687-e11ac200-4114-11ea-9075-fa6d66532973.png)

**Comment by NMAAHC** [comment]
found it! Thanks! will continue some more testing :)
